<nav class="filter-nav" id=js-filter-nav>
	<div class="options" id="options">
		<div class="options-wrapper">
			<input class="filter" id="showBreakfast" type=radio name="filter" value="breakfast">
			<label for="showBreakfast">
				<nobr>Ontbijt</nobr>
			</label>
		</div>
		<div class="options-wrapper">
			<input class="filter" id="showLunch" type=radio name="filter" value="lunch">
			<label for="showLunch">
				<nobr>Lunch</nobr>
			</label>
		</div>
		<div class="options-wrapper">
			<input class="filter" id="showCoffee" type=radio name="filter" value="coffe">
			<label for="showCoffee">
				<nobr>Taart</nobr>
			</label>
		</div>
		<div class="options-wrapper">
			<input class="filter" id="showDinner" type=radio name="filter" value="dinner">
			<label for="showDinner">
				<nobr>Diner</nobr>
			</label>
		</div>
		<div class="options-wrapper">
			<input class="filter" id="showAll" type=radio name="filter" value="all" checked>
			<label for="showAll">
				<nobr>Alles</nobr>
			</label>
		</div>
	</div>
</nav>